apiVersion: v2
name: release-tracker
description: Helm chart for the Release Tracker application
home: https://github.com/rogosprojects/helm.git
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/helm/icon/color/helm-icon-color.png
type: application
version: 0.1.2
appVersion: "0.1.0"
keywords:
  - kubernetes
  - releases
  - tracking
  - dashboard
sources:
  - https://github.com/rogosprojects/helm.git
maintainers:
  - name: Maintainers
    email: devnull@example.com

