apiVersion: v2
name: kpods-monitor
description: A Helm chart for Kubernetes Pod Monitor
type: application
version: 0.2.5
appVersion: "0.2.2"
keywords:
  - kubernetes
  - monitoring
  - pods
home: https://github.com/rogosprojects/kpods-monitor
